
algorithms:
    production: 'Renes Hybrid'
    production_var: 'Renes Hybrid STD'
    consumption: 'Baseline Finder'

    advise-unit: 'informed' # 'ev-advise' or 'dummy' or 'informed' or 'delayed' or 'informed-delayed'

truth:
    consumption: 'House Consumption'
    production: 'WTG Production'

dataset:
    filename: 'dataset-kw.gz'
    timezone: 'Europe/Zurich'

adjustment:
    wtg-scale: 1
    house-scale: 1

dates:
    month: 'january' # 'january' or 'december'

location: 'UK' # 'UK' or 'US'

random-seed: 1337

battery:
    soc-range:
        min: 0.2
        max: 0.8

    actions: 'all' # 'all', 'five' or 'two'


delay:
    hour: 22
    minute: 00