
algorithms:
    production: 'Renes Hybrid'
    production_var: 'Renes Hybrid STD'
    consumption: 'Baseline Finder'

truth:
    consumption: 'House Consumption'
    production: 'WTG Production'

dataset:
    filename: 'dataset-kw.gz'
    timezone: 'Europe/Zurich'

prices:
    usage_cost_key: 'Buy Price'
    sell_price_key: 'Sell Price'


adjustment:
    wtg-scale: 1
    house-scale: 1

random-seed: 1337

battery:
    soc-range:
        min: 0.2
        max: 0.8

    actions: 'two' # 'all', 'five' or 'two'
