dataset:
    filename: 'dataset-kw.gz'
    timezone: 'Europe/Zurich'

adjustment:
    wind-scale: 3
    solar-scale: 40
    house-scale: 1

random-seed: 1337

battery:
    soc-range:
        min: 0.2
        max: 0.8

    actions: 'five' # 'all', 'five' or 'two'
